spring:

  application:
    name: hopematch_backend

  datasource:
    url: jdbc:mysql://database-hopematch.c43c20s6kc2e.us-east-1.rds.amazonaws.com:3306/hopematch
    username: root
    password: mysqlroosevelt14

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl:
        auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  jwt:
    secret: unaClaveSecretaMuySecretaDeAlMenos256BitsEsUnaClaveLargaJAJA
    expiration: 86400000  # 1000 * 60 * 60 * 24 = 24 horas en milisegundos

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE